#ifndef WIFI_ICON16X16_H
#define WIFI_ICON16X16_H

#include <stdint.h>

// -------------------------------------------------------
// Generated by Guardian LTSM - One Bit Converter
// Image Name  : wifi_icon16x16
// Dimensions  : 16 x 16 px
// Data Size   : 32 bytes
// Draw Mode   : Horizontal
// Swap Bits   : No
// Threshold   : 128
// Inverted    : No
// -------------------------------------------------------

const uint8_t wifi_icon16x16[] = {
    0x1F, 0xF8, 0x60, 0x06, 0x80, 0x01, 0x00, 0x00, 0x0F, 0xF0, 0x30, 0x0C, 0x00, 0x00, 0x03, 0xC0,
    0x04, 0x20, 0x00, 0x00, 0x01, 0x80, 0x01, 0x80, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

#endif // WIFI_ICON16X16_H
